# Generated by Django 6.1 on 2026-08-11 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Name of inventory owner', max_length=150, verbose_name='fullname')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('last_used', models.DateTimeField(auto_now_add=True, verbose_name='last used')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='info', max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='entity')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryowner', verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, null=True, unique=True, verbose_name='inventory number')),
                ('serial_number', models.CharField(blank=True, null=True, unique=True, verbose_name='serial number')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorygroup', verbose_name='group')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='location')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.photo', verbose_name='photo')),
                ('tags', models.ManyToManyField(to='inventory.tag', verbose_name='tags')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVE', 'ARCHIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem', verbose_name='inventory item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='location')),
            ],
        ),
    ]
