# Generated by Django 6.1 on 2026-08-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationhistory',
            options={'verbose_name': 'Location history', 'verbose_name_plural': 'Location histories'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.photo', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
